#name: Build and push Docker image

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_USERNAME: kev74
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Print current working directory
        run: pwd
      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_HUB_USERNAME }}/tp2:${{ github.sha }} .

      - uses: docker/login-action@v1
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ DOCKER_HUB_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push ${{ env.DOCKER_HUB_USERNAME }}/tp2:${{ github.sha }}
