on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_USERNAME: kev74
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}


jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/checkout@v3
      - name: Check Dockerfile syntax
        uses: hadolint/hadolint-action@v3.1.0
        id: hadolint
        with:
          dockerfile: Dockerfile
      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_HUB_USERNAME }}/tp2:${{ github.sha }} .
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}


      - name: Push Docker image
        run: docker push ${{ env.DOCKER_HUB_USERNAME }}/tp2:${{ github.sha }}
        
      - name: List files in the repository
        run: |
              echo "${{ steps.hadolint.outputs.result }}"
